### PR TITLE
Fix #16: Make testkit framework independent

### LINKED ISSUE #15: Move test utils out of tests
The module `tests` sounds more like a test-harness for the `scala-bricks` project only, rather than a module of re-usable test utilities.

So, move `tests/src/main` to `testkit/src/main`

Credit for the name `testkit` to @rossabaker in https://github.com/non/cats/issues/529

### LINKED ISSUE #16: Make testkit framework independent
As suggested by @rossabaker https://github.com/non/cats/issues/529

### PR DESCRIPTION
**Pull request by InTheNow**
Fix #15
Fix #16

Pretty big changes, but once this PR is done things should settle down. Main change is addition of Spec2.

@non, @milessabin Please can you review?

### CODE REVIEW

**Comment by non** [comment]
Sure, I'll review it. It's going to take me a minute to read this carefully.

**Comment by non** [comment]
LGTM :+1: (assuming we get tests passing and such)

**Comment by milessabin** [comment]
:+1: ... what @non said ...

**Comment by InTheNow** [comment]
OK, looking good.

Also, welcome to @ochrons and @adelbertc to the team :clap:

**Comment by ochrons** [comment]
LGTM2

**Pull request merged**
